services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://127.0.0.1:8000"
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://127.0.0.1:5000
    restart: unless-stopped